baseapp/urls.py
from django.urls import path, include
from baseapp import views

app_name = "baseapp"

urlpatterns = [
    path("", views.home, name="HomePage"),
    path("register-user", views.register, name="register_user"),
    path("login-user", views.login_user, name="login_user"),
    path("login-user", views.logout_user, name="logout_user"),
    path("check-pet-health", views.check_pet_health, name="get_pet_health"),
    path("pet-adoption-status", views.pet_adoption_status, name="pet_adoption_status"),
    path("querytest", views.query_test, name="querytest"),
    path("faq-page", views.faq_page, name="faq_page"),
    path("pet-adoption-page", views.pet_adoption_page, name="pet_adoption_page"),
    path("pet-adoption-form", views.pet_adoption_form, name="pet_adoption_form"),
    path("pet_list", views.pet_list, name="pet_list"),
]

pawsitive/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("baseapp.urls")),
]

templates/adoption_status.html
{% extends "base.html" %}

{% load static %}

{% block css %}
<style>
    .calculator {
        background-color: #130000;
        /* padding: 20px; */
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        /* max-width: 400px; */

        /* width: 100%; */
        max-width: 30%;
        position: absolute;
        top: 25%;
        left: 35%;
        transform: translateX(-50%, -50%);

    }

    h2 {
        text-align: center;
        color: white;
    }

    label {
        font-weight: bold;
    }

    input {
        width: 95%;
        padding: 8px;
        margin-bottom: 10px;
        border: none;
        border-bottom: 1px solid #ccc;
        color: white;
    }

    input::placeholder {
        color: white
    }

    button {
        width: 100%;
        padding: 10px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

    button:hover {
        background-color: #0056b3;
    }

    #investmentForm input {
        background-color: transparent;
        color: white;
    }

    #result {
        color: white;
    }
</style>
<link rel="stylesheet" href="{% static 'css/calc.css' %}">
{% endblock %}


{% block body %}
<div class="calculator">
    <h2>Check Adoption Status &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </h2>
    <form action="{% url 'baseapp:pet_adoption_status' %}" method="post">
        {% csrf_token %}
        <label for="requestID">RequestID:</label><br>
        <input type="number" id="request_id" name="request_id"><br>
        <label for="petID">PetID:</label><br>
        <input type="number" id="pet_id" name="pet_id"><br>
        <label for="requesterID">RequesterID:</label><br>
        <input type="number" id="requester_id" name="requester_id"><br>
        <label for="requestDate">Request Date:</label><br>
        <input type="date" id="requestDate" name="request_date"><br><br>
        <button type="submit" value="Submit">Check Status </button>
    </form>
    {% if adoption_status %}
    <div id="result" >
        <p>{{ adoption_status.Approval_Status }}</p>
    </div>
    {% endif %}
</div>
{% endblock %}



{% block script %}

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />

    <style></style>
    <!-- ---------------------------- CSS BLOCK ----------------------------- -->
    {% block css %} {% endblock %}
</head>

<body>
    <!-- ---------------------------- BODY BLOCK ----------------------------- -->

    <!-- Navbar -->
    <div class="navbar" id="navbar">
        <a href="{% url 'baseapp:HomePage' %}"><img width="80rem" src="{% static 'images/pawsitive.svg' %}"
                alt="" /></a>
        <a href="{% url 'baseapp:HomePage' %}" class="active">Home</a>
        <select class="dropbtn" onchange="navigateToPage(this.value)">
            <option value="" disabled selected>Check</option>
            <option value="{% url 'baseapp:get_pet_health' %}">Pet Health</option>
            <option value="{% url 'baseapp:pet_adoption_status' %}">Adoption Request Status</option>
        </select>

        <select class="dropbtn" onchange="navigateToPage(this.value)" name="DebtManager" id="debtmanager">
            <option value="" disabled selected>Hub</option>
            <option value="">Learn&grow</option>
            <option value="">Post</option>
        </select>

        <select class="dropbtn" onchange="navigateToPage(this.value)" name="saving sprint" id="saving-sprint"
            class="saving-sprint">
            <option value="" disabled selected>Lets Adopt</option>
            <option value="{% url 'baseapp:pet_adoption_page' %}">Adopt</option>
        </select>
        <a href="javascript:void(0);" class="icon" onclick="toggleNavbar()"> &#9776; </a>
        <!-- <a href="" class="active">FAQ</a>+ -->
        <!-- <a href="{% url 'baseapp:querytest' %}" class="active">Querytest</a>    -->
        <a href="{% url 'baseapp:faq_page' %}" class="active">FAQs</a>



        {% if user.is_authenticated %}
        <a class="anchor-btn" href="{% url 'baseapp:logout_user' %}">{{ request.user.username }}</a>
        {% else %}
        <a class="anchor-btn" href="{% url 'baseapp:login_user' %}">Login</a>
        {% endif %}
    </div>

    <!-- Content -->
    {% block content %} {% endblock %}

    <div class="container">{% block body %} {% endblock %}</div>

    <!-- ---------------------------- SCRIPT BLOCK ----------------------------- -->
    {% block script %} {% endblock %}

    <!-- JavaScript to toggle responsive navbar -->

    <script>
        function toggleNavbar() {
            var x = document.getElementById("navbar");
            if (x.className === "navbar") {
                x.className += " responsive";
            } else {
                x.className = "navbar";
            }
        }
    </script>
    <script>
        function navigateToPage(url) {
            if (url) {
                window.location.href = url;
            }
        }
    </script>
</body>

</html>

templates/faq.html
{% extends "base.html" %}

{% load static %}

{% block title %} FAQs {% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/faq.css' %}">

{% endblock %}
{% block body %}
<div class="faq-background">
    <div class="faq-container">
        <img class="faq-trn-logo" src="{% static 'images/trn_logo.png' %}" alt="" />
        <h1 style="color: white; font-weight: 300;" >You have questions </h1>
        <h3>
            We are ready with our solutions 
        </h3>
    </div>
</div>

<div class="faq-items">
    <div class="faq-container">

        {% for i in faq_data %}
        <div class="faq-item">
            <h3 class="question"> {{ i.question }} </h3>
            <div class="answer">
                <p>
                    {{ i.answer }}
                   
                </p>
            </div>
        </div>
        {% endfor %}

    </div>
</div>
{% endblock %} {% block script %}
<script>
    document.addEventListener("DOMContentLoaded", function () {
        const questions = document.querySelectorAll(".question");
        questions.forEach((question) => {
            question.addEventListener("click", function () {
                const answer = this.nextElementSibling;
                const isOpen = answer.style.display === "block";
                // Close other div
                questions.forEach((q) => {
                    const a = q.nextElementSibling;
                    if (a !== answer) {
                        a.style.display = "none";
                    }
                });
                // Toggle current answer
                answer.style.display = isOpen ? "none" : "block";
            });
        });
    });
</script>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% load static %}

{% block css %}
<!-- tailwindcss -->
<link href="https://cdn.jsdelivr.net/npm/daisyui@2.6.0/dist/full.css" rel="stylesheet" type="text/css" />
<script src="https://cdn.tailwindcss.com"></script>
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<style>
    .main-index-div {
        display: flex;
        flex-direction: column;
        align-items: flex-end;
        /* Set the height of the container to the full viewport height */
        width: 100%;
    }

    .text {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100%;
        background-color: greenyellow;
        /* Adjust margin as needed */
    }


    .main-div {
        width: 100%;
        height: 56rem;
        background-color: white;
    }

    #mainhead {
        margin-bottom: 10%;

    }

    #head-id {
        padding-top: 5rem;
        margin-left: 10%;
        font-size: 4rem;
    }

    #headimg {
        margin-left: 60%;
        margin-top: -25%;
    }

    footer nav a,
    footer nav h6 {
        background-color: transparent;
    }

    .footer-logo {
        width: 10rem;
        mix-blend-mode: lighten;
    }

    .home-container {
        display: flex;
        justify-content: space-around;
    }

    .home-section {
        text-align: center;
    }

    .home-section h2 {
        font-size: 3rem;
    }

    .home-section p {
        font-size: 1.5rem;
    }


    .img-text-container {
        display: flex;
        align-items: center;
        /* Center items vertically */
    }

    #img2 {
        margin-top: 10%;
        width: 40%;
        margin-left: 9%;
        /* Adjust width as needed */
        margin-right: 20px;
        /* Margin between image and text */

    }

    .mytext {
        flex: 1;
        /* Take up remaining space */
        margin-left: 10%;
        margin-top: 8%;

    }

    #h1txt {
        font-size: 3rem;
    }
</style>
{% endblock %}


{% block body %}

<div class="head-text">
    <h1 id="head-id"><a class="anchor-btn" style="color:white" href="">Adopt</a><span style="color: rgb(0, 170, 255);">
            <br>Virtually </span> Help <br> Physically</h1>
    <p style="margin-left: 10%; font-size: 1.1rem;">Approximately 1478 dogs & cats die every day on road in India.<br>
        PAWsitive is on a mission to provide every dog and cat a home before 2035.<br>
        By making you adopt them vitually !!
</div>

<div class="first-section-image">
    <img id="headimg" src="{% static 'images/hero_image.svg' %}" alt="home pic ">
</div>

<div class="home-container" style="margin-top: 5%;">
    <div class="home-section" style="margin-right: 0.002%">
        <h2 style="color: aqua;">Search</h2>
        <p></p>
    </div>
    <div class="home-section">
        <h2 style="color: aqua;">Adopt</h2>
        <p>Virtually</p>
    </div>
    <div class="home-section">
        <h2 style="color: aqua;">Learn </h2>
        <p></p>
    </div>
</div>



<div class="spacing" style="margin-top: 8%;"></div>

<footer class="footer p-10 bg-gray-900  text-base-content">
    <aside class="bg-transparent">
        <img class="footer-logo" src="{% static 'images/finvizer.svg' %}" alt="">
        <p class="bg-transparent">ACME Industries Ltd.<br>Providing reliable tech since 1992</p>
    </aside>
    <nav class="bg-transparent">
        <h6 class="footer-title">Services</h6>
        <a class="link link-hover">Branding</a>
        <a class="link link-hover">Design</a>
        <a class="link link-hover">Marketing</a>
        <a class="link link-hover">Advertisement</a>
    </nav>
    <nav class="bg-transparent">
        <h6 class="footer-title">Company</h6>
        <a class="link link-hover">About us</a>
        <a class="link link-hover">Contact</a>
        <a class="link link-hover">Jobs</a>
        <a class="link link-hover">Press kit</a>
    </nav>
    <nav class="bg-transparent">
        <h6 class="footer-title">Legal</h6>
        <a class="link link-hover ">Terms of use</a>
        <a class="link link-hover ">Privacy policy</a>
        <a class="link link-hover ">Cookie policy</a>
    </nav>
</footer>
</div>


{% endblock body %}


<!-- withdrawl option
dynamic percentage 
compare expected % -->

templates/pet_adoption_form.html
{% extends "base.html" %} {% load static %} {% block css %}
<style>
  .calculator {
    background-color: transparent;
    padding: 35px;
    border: solid 1px white;
    border-radius: 8px;

    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    /* max-width: 400px; */

    /* width: 100%; */
    max-width: 30%;
    position: absolute;
    top: 25%;
    left: 35%;
    transform: translateX(-50%, -50%);
  }

  h2 {
    text-align: center;
    color: white;
  }

  label {
    font-weight: bold;
  }

  input {
    width: 95%;
    margin-bottom: 10px;
    border: none;
    border-bottom: 1px solid #ccc;
    color: white;
  }

  input::placeholder {
    color: white;
  }

  button {
    width: 100%;
    padding: 10px;
    background-color: #007bff;
    color: #fff;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    transition: background-color 0.3s ease;
  }

  button:hover {
    background-color: #0056b3;
  }

  #investmentForm input {
    background-color: transparent;
    color: white;
  }

  #result {
    color: white;
  }
</style>
<link rel="stylesheet" href="{% static 'css/calc.css' %}" />
{% endblock %} {% block body %}
<div class="calculator">
  <h2>Pet Information Form</h2>
  <form action="{% url 'baseapp:pet_adoption_form' %}" method="POST">
    {% csrf_token %}
    <input type="text" id="petName" name="petName" placeholder="Pet Name" required maxlength="50" /><br /><br />

    <input type="text" id="species" name="species" required maxlength="50" placeholder="Species" /><br /><br />

    <input type="text" id="breed" name="breed" required maxlength="50" placeholder="Breed" /><br /><br />

    <input type="number" id="age" name="age" required min="0" max="999" placeholder="Age" /><br /><br />

    <!-- <label for="gender">Gender:</label><br> -->
    <select id="gender" name="gender" aria-placeholder="gener" required>
      <option value="male">Male</option>
      <option value="female">Female</option>
      <option value="other">Other</option>
    </select><br /><br />

    <button type="submit">Submit</button>
  </form>
  {% if adoption_status %}
  <div id="result">
    <p>{{ adoption_status.Approval_Status }}</p>
  </div>
  {% endif %}
</div>
{% endblock %} {% block script %} {% endblock %}

templates/pet_health_check.html
{% extends "base.html" %}


{% block css %}

<style>
    .calculator {
        /* background-color: #fff; */
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        max-width: 400px;
        width: 120%;
        position: absolute;
        top: 25%;
        left: 35%;
        transform: translateX(-50%, -50%);
    }

    h2 {
        text-align: center;
        color: white;
    }

    label {
        font-weight: bold;
    }

    input {
        width: 95%;
        padding: 8px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border: none;
        border-bottom: 1px solid white;
        color: white;
    }

    input::placeholder {
        color: white;
    }

    button {
        width: 100%;
        padding: 10px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

    button:hover {
        background-color: #0056b3;
    }

    #result {
        margin-top: 20px;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
    }
</style>
{% endblock %}


{% block body %}
<div class="calculator">
    <h2>Get Your Pet's Health</h2>
    <form action="{% url 'baseapp:get_pet_health' %}" method="post">
        {% csrf_token %}
        <label for="logID">LogID:</label><br>
        <input type="number" id="logID" name="logID"><br>
        <label for="petID">PetID:</label><br>
        <input type="number" id="petID" name="petID"><br>
        <label for="petName">Pet Name:</label><br>
        <input type="text" id="petName" name="petName"><br><br>
        <button type="submit" value="Submit">Check Status</button>
    </form>

    {% if pet %}
    <div id="result">
        {{ pet.Health_Status }}
    </div>
    {% endif %}
</div>
{% endblock %}


{% block script %}

{% endblock %}